// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { env } from '@/utils/env';

// ✅ SECURE: Use centralized environment configuration
export const supabase = createClient<Database>(env.supabase.url, env.supabase.anonKey, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  // Enable public access for review form submissions
  db: {
    schema: 'public'
  },
  global: {
    headers: {
      'X-Client-Info': 'supabase-js/2.0.0'
    }
  }
});

// Create a public client for unauthenticated operations
// This client is specifically for anonymous users submitting reviews
export const supabasePublic = createClient<Database>(env.supabase.url, env.supabase.anonKey, {
  auth: {
    persistSession: false,
    autoRefreshToken: false,
    detectSessionInUrl: false,
  },
  db: {
    schema: 'public'
  },
  global: {
    headers: {
      'X-Client-Info': 'supabase-js/2.0.0'
    }
  }
});

// Helper function to check if Supabase is properly configured
export const isSupabaseConfigured = () => {
  return env.supabase.url !== 'https://elhbthnvwcqewjpwulhq.supabase.co' || 
         env.supabase.anonKey !== 'placeholder_key';
};