// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { env } from '@/utils/env';

// ✅ SECURE: Use centralized environment configuration
export const supabase = createClient<Database>(env.supabase.url, env.supabase.anonKey, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  // Enable public access for review form submissions
  db: {
    schema: 'public'
  }
});

// Create a public client for unauthenticated operations
export const supabasePublic = createClient<Database>(env.supabase.url, env.supabase.anonKey, {
  auth: {
    persistSession: false,
    autoRefreshToken: false,
  },
  db: {
    schema: 'public'
  }
});