// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://elhbthnvwcqewjpwulhq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVsaGJ0aG52d2NxZXdqcHd1bGhxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0NDU2NzAsImV4cCI6MjA3MjAyMTY3MH0.sUTEsRkzPbS2gGFOB_kMCgdqEQWNBKRi51wTrhD-VkY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});